extends Node

var _LEVEL = 1

var STR = 5
var DEX = 5
var INT = 5

var BASE_HP = 40
var BASE_MP = 15

var _EMPTY_POINT = 5

var _PLAYER_LEVEL = 1
var _MAX_EXP = 400
var _EXP = 0
var _MAX_MANA = BASE_MP + round(INT * 2)
var _MAX_HEALTH = BASE_HP + round(STR * 2)
var _HEALTH = _MAX_HEALTH
var _MANA = _MAX_MANA

var _LIFE_FLASK_CHARHE = 40

var ARMOR 
var EVASION
var SPELL_EVASION

var MOVE_SPEED
var MELEE_ATACK_SPEED
var RANGE_ATTACK_SPEED 
var SPELL_ATTACK_SPEED
var SPEED

var REDUCE_DAMAGE 
var REDUCE_SPELL 

var CHANCE_MELEE_HIT 
var CHANCE_RANGE_HIT 
var CHANCE_SPELL_HIT 

var _BASE_DAMAGE
var _RANGE_DAMAGE

var EVASION_RATING
var SPELL_EVASION_RATING 
var STUN_ON_HIT_RATING 
var STUN_ON_SPELL_HIT_RATING 

func _process(delta):
	ARMOR = STR / 2
	EVASION = DEX / 2
	SPELL_EVASION = INT / 2

	EVASION_RATING = 30 + DEX * 1.5 + EVASION 
	SPELL_EVASION_RATING = 30 + INT * 1.5 + SPELL_EVASION 
	STUN_ON_HIT_RATING = 30 + STR + DEX / 2
	STUN_ON_SPELL_HIT_RATING = 30 + INT + DEX / 2

	MOVE_SPEED = 1 + (STR / 2 * DEX / 2) / 100
	MELEE_ATACK_SPEED = 1 + (STR / 2) / 100 
	RANGE_ATTACK_SPEED = 1 + (DEX / 2) / 100 
	SPELL_ATTACK_SPEED = 1 + (INT / 2) / 100 

	REDUCE_DAMAGE = ARMOR / 5 
	REDUCE_SPELL = SPELL_EVASION / 5
	
	SPEED = 100

	CHANCE_MELEE_HIT = 50 + STR * MELEE_ATACK_SPEED 
	CHANCE_RANGE_HIT = 50 + DEX * RANGE_ATTACK_SPEED 
	CHANCE_SPELL_HIT = 50 + INT * SPELL_ATTACK_SPEED 
	
	randomize()

	_BASE_DAMAGE = rand_range(1,4) * (Main.STR / Main.INT)
	_BASE_DAMAGE = int(round(_BASE_DAMAGE)) 
	
	_RANGE_DAMAGE = rand_range(1,6) * (Main.DEX / Main.INT)
	_RANGE_DAMAGE = int(round(_RANGE_DAMAGE)) 


func _PLAYER_LEVEL_UP():
	_PLAYER_LEVEL += 1
	_EMPTY_POINT += 5
	_MAX_HEALTH = BASE_HP + round(STR * 2)
	_HEALTH = _MAX_HEALTH
	_MAX_MANA = BASE_MP + round(INT * 2)
	_MANA = _MAX_MANA


